"""
Django settings for demo_app project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from os import environ
from pathlib import Path
from dotenv import load_dotenv


# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# ========================================================== SECURITY SECTION ==================================================================

SECRET_KEY = environ.get("APPDJANGO_KEY", "")
FIELD_ENCRYPTION_KEY = environ.get("FIELD_ENCRYPTION_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Specify allowed hosts (your Wildfly server's IP domain)
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "your_wildfly_ip_or_domain"]

# The list of extra HTTP headers to expose to the browser, in addition to the default safelisted headers.
# If non-empty, these are declared in the access-control-expose-headers header. Defaults to [].
CORS_EXPOSE_HEADERS = ["Content-Type", "X-CSRFToken"]

# If True, cookies will be allowed to be included in cross-site HTTP requests
CORS_ALLOW_CREDENTIALS = True

# corsheaders - A list of origins that are authorized to make cross-site HTTP requests. The origins in this setting will be allowed,
# and the requesting origin will be echoed back to the client in the access-control-allow-origin header. Defaults to [].
CORS_ALLOWED_ORIGINS = [
    "https://example.com",
    "https://sub.example.com",
    "http://localhost:8080",
    "http://127.0.0.1:9000",
    "http://your_wildfly_ip_or_domain:port"
]

# CSRF Integration
# Most sites will need to take advantage of the Cross-Site Request Forgery protection that Django offers. CORS and CSRF are separate, 
# and Django has no way of using your CORS configuration to exempt sites from the Referer checking that it does on secure requests. 
# The way to do that is with its CSRF_TRUSTED_ORIGINS setting. 
CSRF_TRUSTED_ORIGINS = [
    "https://example.com",
    "https://sub.example.com",
    "http://localhost:8080",
    "http://127.0.0.1:9000",
    "http://your_wildfly_ip_or_domain:port"
]

# ========================================================== SECURITY SECTION ==================================================================

# ========================================================== DJANGO CORE SECTION ===============================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True  # Custom added
USE_TZ = True

# Application definition

INSTALLED_APPS = [
    # These applications are included by default as a convenience for the common case.
    "django.contrib.admin",  # The admin site
    "django.contrib.auth",  # An authentication system.
    "django.contrib.contenttypes",  # A framework for content types.
    "django.contrib.sessions",  # A session framework.
    "django.contrib.messages",  # A messaging framework.
    "django.contrib.staticfiles",  # A framework for managing static files.
    
    # Dependent apps
    "django.contrib.postgres",
    "oauth2_provider",
    "rest_framework",
    "rest_framework.authtoken",
    "encrypted_model_fields",
    "django_filters",
    "drf_spectacular",
    "corsheaders",
    "auditlog",
    "crispy_forms",
    
    # Custom apps
    "app1.apps.App1Config",
    "app2.apps.App2Config",
]

MIDDLEWARE = [
    # Middleware - corsheaders, should be placed as high as possible, especially before any middleware that can generate responses
    # such as Django’s CommonMiddleware or Whitenoise’s WhiteNoiseMiddleware. If it is not before, it will not be able to add the
    # CORS headers to these responses.
    "corsheaders.middleware.CorsMiddleware",
    
    # Default middleware coming from  Django
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
    # django-auditlog middleware
    "auditlog.middleware.AuditlogMiddleware",
]

ROOT_URLCONF = "demo_app.urls"

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly",], 
    
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.FormParser", 
        "rest_framework.parsers.MultiPartParser", 
        
        # Add below for allowing media-type as JSON else we will get this error - "Unsupported Media Type: /question/"
        "rest_framework.parsers.JSONParser",), 
    
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    
    "PAGE_SIZE": 10,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Django Starter API",
    "DESCRIPTION": "API for Django Starter as Example",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # OTHER SETTINGS
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "demo_app.wsgi.application"

# ========================================================== DJANGO CORE SECTION ===============================================================

# ========================================================== DATABASE SECTION ==================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DB_USER_NAME = environ.get("DB_USER_NAME", "").strip()
DB_PWD = environ.get("DB_PWD", "").strip()
DB_NAME = environ.get("DB_NAME", "").strip()
DB_HOST = environ.get("DB_HOST", "").strip()
DB_PORT = environ.get("DB_PORT", "").strip()
DB_SCHEMA_NAME = environ.get("DB_SCHEMA_NAME", "").strip()

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "OPTIONS": {"options": f"-c search_path={DB_SCHEMA_NAME}"},
        "USER": DB_USER_NAME,
        "PASSWORD": DB_PWD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
        # If True, this will cause commit to DB only if all actions for a given web request are successful
        "ATOMIC_REQUESTS": False,
    }
}

SETUP_TESTDB = False
LOAD_FIXTURES = True

# ========================================================== DATABASE SECTION ==================================================================


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
